# Generated by Django 3.0.5 on 2020-05-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfApiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorthEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryDate', models.DateField()),
                ('amount', models.FloatField()),
                ('isPositive', models.BooleanField()),
                ('label', models.ForeignKey(on_delete=models.SET(0), to='pfApiApp.Label')),
            ],
        ),
        migrations.CreateModel(
            name='MonthEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryDate', models.DateField()),
                ('amount', models.FloatField()),
                ('isPositive', models.BooleanField()),
                ('label', models.ForeignKey(on_delete=models.SET(0), to='pfApiApp.Label')),
            ],
        ),
    ]
